services:
  - type: web
    name: social-media-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: "3000"
